server:
  port: 4000
spring:
  application: demo-stream
  cloud:
    stream:
      bindings:
        demo_output:
          destination: demostream
          binder: defaultMq
        demo_input:
          destination: demostream
          binder: defaultMq
          group: abc
      binders:
        defaultMq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.81.30
                port: 5672
                username: root
                password: root
                virtual-host: /zhul

